import nodemailer from "nodemailer";
import type { Briefing, BriefingItem, BriefingContent } from "@/lib/types";

function createTransporter() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT ?? 465),
    secure: process.env.SMTP_SECURE === "true",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_APP_PASSWORD,
    },
  });
}

function buildEmailHtml(briefing: Briefing, items: BriefingItem[]): string {
  const date = new Date(briefing.created_at).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const brandSections = items
    .map((item) => {
      let content: BriefingContent;
      try {
        content = JSON.parse(item.content) as BriefingContent;
      } catch {
        content = {
          summary: item.content,
          key_developments: [],
          why_it_matters: "",
          commercial_implication: "",
        };
      }

      const bullets = content.key_developments
        .map((d) => `<li style="margin: 6px 0;">${d}</li>`)
        .join("");

      const sources = Array.isArray(item.sources)
        ? item.sources
            .map(
              (s) =>
                `<a href="${s.url}" style="color:#881337;font-size:12px;">${s.title}</a>`
            )
            .join(" &nbsp;·&nbsp; ")
        : "";

      return `
      <div style="margin-bottom:32px;padding:20px;background:#fff8f8;border-left:4px solid #881337;border-radius:4px;">
        <h2 style="margin:0 0 12px;font-size:20px;color:#881337;">${item.brand_name}</h2>
        <p style="margin:0 0 12px;font-size:15px;line-height:1.6;color:#1c1917;">${content.summary}</p>
        ${bullets ? `<ul style="padding-left:18px;margin:0 0 12px;color:#1c1917;font-size:14px;line-height:1.6;">${bullets}</ul>` : ""}
        ${content.why_it_matters ? `<p style="margin:0 0 8px;font-size:13px;color:#44403c;"><strong>Why it matters:</strong> ${content.why_it_matters}</p>` : ""}
        ${content.commercial_implication ? `<p style="margin:0 0 12px;font-size:13px;color:#44403c;"><strong>Account manager implication:</strong> ${content.commercial_implication}</p>` : ""}
        ${sources ? `<p style="margin:0;font-size:12px;color:#78716c;"><strong>Sources:</strong> ${sources}</p>` : ""}
      </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Georgia,serif;background:#fafaf9;margin:0;padding:0;">
  <div style="max-width:640px;margin:0 auto;padding:32px 24px;">
    <div style="text-align:center;margin-bottom:28px;">
      <h1 style="font-size:26px;color:#881337;margin:0;">🍷 WineRadar</h1>
      <p style="font-size:13px;color:#78716c;margin:6px 0 0;">Weekly Wine-Market Briefing &nbsp;·&nbsp; ${date}</p>
    </div>
    ${briefing.summary ? `<p style="font-size:15px;color:#1c1917;background:#fff;border:1px solid #e7e5e4;border-radius:6px;padding:16px;margin-bottom:28px;">${briefing.summary}</p>` : ""}
    ${brandSections}
    <div style="margin-top:40px;padding-top:20px;border-top:1px solid #e7e5e4;text-align:center;">
      <p style="font-size:11px;color:#a8a29e;">Generated by WineRadar &nbsp;·&nbsp; Your weekly wine-market intelligence</p>
    </div>
  </div>
</body>
</html>`;
}

export async function sendBriefingEmail(
  recipientEmail: string,
  briefing: Briefing,
  items: BriefingItem[]
): Promise<void> {
  const transporter = createTransporter();
  const html = buildEmailHtml(briefing, items);

  const date = new Date(briefing.created_at).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  await transporter.sendMail({
    from: process.env.SMTP_FROM_EMAIL,
    to: recipientEmail,
    subject: `WineRadar Weekly Briefing – ${date}`,
    html,
  });
}
